apiVersion: v1
kind: Service
metadata:
  name: petclinic-dev
  labels:
    app: petclinic-dev
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic-dev
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-replication-controller-dev
  labels: 
    app: petclinic-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic-dev
        tier: frontend
    spec:
      imagePullSecrets:
        - name: dockerpullcredentials
      containers:
      - image: nexus.itgo-devops.org:18444/admin/petclinic:198
        name: petclinic-dev
        env:
          - name: ENV_COMPONTENT_NAME
            value: "Petclinic-dev-frontend"        
          - name: ENV_PRODUCT_NAME
            value: "Petclinic-dev"             
          - name: ENV_KUBERNETES_POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ENV_KUBERNETES_NS
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: http

## Need to create a secret key that the Pods are able to pull the private registry
## the user has readonly permissions to the hit-repository (see Nexus config) 
# kubectl create secret docker-registry dockerpullcredentials --docker-server=nexus.itgo-devops.org:18444 --docker-username=docker-pull-user --docker-password=123456 --docker-email=docker-pull-user@itergo.com
